# Generated by Django 5.0 on 2026-08-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='productos/videos/'),
        ),
    ]
