# Generated by Django 5.0 on 2026-08-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
